const TAROT_DECK = [
  // ── MAJOR ARCANA ──────────────────────────────────────────────────────────
  { name: "0 The Fool",            suit: "major", num: 0,  zhName: "0 愚者",         aliases: ["0","zero","fool","the fool","0 the fool"],                                                                   zhAliases: ["愚者","愚人"] },
  { name: "I The Magician",        suit: "major", num: 1,  zhName: "I 魔術師",       aliases: ["1","i","one","magician","the magician","i the magician"],                                                    zhAliases: ["魔術師","魔法師"] },
  { name: "II The High Priestess", suit: "major", num: 2,  zhName: "II 女祭司",      aliases: ["2","ii","two","high priestess","priestess","the high priestess","ii the high priestess"],                    zhAliases: ["女祭司","祭司"] },
  { name: "III The Empress",       suit: "major", num: 3,  zhName: "III 女皇",       aliases: ["3","iii","three","empress","the empress","iii the empress"],                                                  zhAliases: ["女皇"] },
  { name: "IV The Emperor",        suit: "major", num: 4,  zhName: "IV 皇帝",        aliases: ["4","iv","four","emperor","the emperor","iv the emperor"],                                                    zhAliases: ["皇帝"] },
  { name: "V The Hierophant",      suit: "major", num: 5,  zhName: "V 教皇",         aliases: ["5","v","five","hierophant","pope","the hierophant","v the hierophant"],                                      zhAliases: ["教皇","教宗"] },
  { name: "VI The Lovers",         suit: "major", num: 6,  zhName: "VI 戀人",        aliases: ["6","vi","six","lovers","the lovers","vi the lovers"],                                                        zhAliases: ["戀人","愛人"] },
  { name: "VII The Chariot",       suit: "major", num: 7,  zhName: "VII 戰車",       aliases: ["7","vii","seven","chariot","the chariot","vii the chariot"],                                                zhAliases: ["戰車"] },
  { name: "VIII Strength",         suit: "major", num: 8,  zhName: "VIII 力量",      aliases: ["8","viii","eight","strength","fortitude","viii strength"],                                                  zhAliases: ["力量"] },
  { name: "IX The Hermit",         suit: "major", num: 9,  zhName: "IX 隱士",        aliases: ["9","ix","nine","hermit","the hermit","ix the hermit"],                                                      zhAliases: ["隱士"] },
  { name: "X Wheel of Fortune",    suit: "major", num: 10, zhName: "X 命運之輪",     aliases: ["10","x","ten","wheel","wheel of fortune","fortune","x wheel of fortune"],                                   zhAliases: ["命運之輪","命運","輪盤"] },
  { name: "XI Justice",            suit: "major", num: 11, zhName: "XI 正義",        aliases: ["11","xi","eleven","justice","xi justice"],                                                                   zhAliases: ["正義"] },
  { name: "XII The Hanged Man",    suit: "major", num: 12, zhName: "XII 倒吊人",     aliases: ["12","xii","twelve","hanged man","hanged","the hanged man","xii the hanged man"],                            zhAliases: ["倒吊人","倒吊","吊人"] },
  { name: "XIII Death",            suit: "major", num: 13, zhName: "XIII 死神",      aliases: ["13","xiii","thirteen","death","xiii death"],                                                                 zhAliases: ["死神","死亡"] },
  { name: "XIV Temperance",        suit: "major", num: 14, zhName: "XIV 節制",       aliases: ["14","xiv","fourteen","temperance","xiv temperance"],                                                        zhAliases: ["節制"] },
  { name: "XV The Devil",          suit: "major", num: 15, zhName: "XV 惡魔",        aliases: ["15","xv","fifteen","devil","the devil","xv the devil"],                                                     zhAliases: ["惡魔","魔鬼"] },
  { name: "XVI The Tower",         suit: "major", num: 16, zhName: "XVI 高塔",       aliases: ["16","xvi","sixteen","tower","the tower","xvi the tower"],                                                   zhAliases: ["高塔","塔"] },
  { name: "XVII The Star",         suit: "major", num: 17, zhName: "XVII 星星",      aliases: ["17","xvii","seventeen","star","the star","xvii the star"],                                                   zhAliases: ["星星","星"] },
  { name: "XVIII The Moon",        suit: "major", num: 18, zhName: "XVIII 月亮",     aliases: ["18","xviii","eighteen","moon","the moon","xviii the moon"],                                                  zhAliases: ["月亮","月"] },
  { name: "XIX The Sun",           suit: "major", num: 19, zhName: "XIX 太陽",       aliases: ["19","xix","nineteen","sun","the sun","xix the sun"],                                                        zhAliases: ["太陽","日"] },
  { name: "XX Judgement",          suit: "major", num: 20, zhName: "XX 審判",        aliases: ["20","xx","twenty","judgement","judgment","xx judgement"],                                                    zhAliases: ["審判","末日"] },
  { name: "XXI The World",         suit: "major", num: 21, zhName: "XXI 世界",       aliases: ["21","xxi","twenty one","twenty-one","world","the world","xxi the world"],                                    zhAliases: ["世界"] },

  // ── MINOR ARCANA — CUPS ───────────────────────────────────────────────────
  { name: "1 of Cups",           suit: "cups", num: 1,  zhName: "聖盃王牌", aliases: ["ace","1","i","one","ace of cups","1 of cups"],                 zhAliases: ["聖盃","聖杯","聖盃王牌","聖杯王牌","聖盃一","王牌","聖盃1"] },
  { name: "2 of Cups",           suit: "cups", num: 2,  zhName: "聖盃二",   aliases: ["2","ii","two","two of cups","2 of cups"],                     zhAliases: ["聖盃","聖杯","聖盃二","聖杯二","聖盃2"] },
  { name: "3 of Cups",           suit: "cups", num: 3,  zhName: "聖盃三",   aliases: ["3","iii","three","three of cups","3 of cups"],                 zhAliases: ["聖盃","聖杯","聖盃三","聖杯三","聖盃3"] },
  { name: "4 of Cups",           suit: "cups", num: 4,  zhName: "聖盃四",   aliases: ["4","iv","four","four of cups","4 of cups"],                   zhAliases: ["聖盃","聖杯","聖盃四","聖杯四","聖盃4"] },
  { name: "5 of Cups",           suit: "cups", num: 5,  zhName: "聖盃五",   aliases: ["5","v","five","five of cups","5 of cups"],                   zhAliases: ["聖盃","聖杯","聖盃五","聖杯五","聖盃5"] },
  { name: "6 of Cups",           suit: "cups", num: 6,  zhName: "聖盃六",   aliases: ["6","vi","six","six of cups","6 of cups"],                   zhAliases: ["聖盃","聖杯","聖盃六","聖杯六","聖盃6"] },
  { name: "7 of Cups",           suit: "cups", num: 7,  zhName: "聖盃七",   aliases: ["7","vii","seven","seven of cups","7 of cups"],               zhAliases: ["聖盃","聖杯","聖盃七","聖杯七","聖盃7"] },
  { name: "8 of Cups",           suit: "cups", num: 8,  zhName: "聖盃八",   aliases: ["8","viii","eight","eight of cups","8 of cups"],             zhAliases: ["聖盃","聖杯","聖盃八","聖杯八","聖盃8"] },
  { name: "9 of Cups",           suit: "cups", num: 9,  zhName: "聖盃九",   aliases: ["9","ix","nine","nine of cups","9 of cups"],                 zhAliases: ["聖盃","聖杯","聖盃九","聖杯九","聖盃9"] },
  { name: "10 of Cups",          suit: "cups", num: 10, zhName: "聖盃十",   aliases: ["10","x","ten","ten of cups","10 of cups"],                   zhAliases: ["聖盃","聖杯","聖盃十","聖杯十","聖盃10"] },
  { name: "Page of Cups",        suit: "cups", num: 11, zhName: "聖盃侍者", aliases: ["11","xi","page","page of cups"],                             zhAliases: ["聖盃","聖杯","聖盃侍者","聖杯侍者","侍者"] },
  { name: "Knight of Cups",      suit: "cups", num: 12, zhName: "聖盃騎士", aliases: ["12","xii","knight","knight of cups"],                         zhAliases: ["聖盃","聖杯","聖盃騎士","聖杯騎士","騎士"] },
  { name: "Queen of Cups",       suit: "cups", num: 13, zhName: "聖盃王后", aliases: ["13","xiii","queen","queen of cups"],                         zhAliases: ["聖盃","聖杯","聖盃王后","聖杯王后","王后"] },
  { name: "King of Cups",        suit: "cups", num: 14, zhName: "聖盃國王", aliases: ["14","xiv","king","king of cups"],                           zhAliases: ["聖盃","聖杯","聖盃國王","聖杯國王","國王"] },

  // ── MINOR ARCANA — WANDS ──────────────────────────────────────────────────
  { name: "1 of Wands",          suit: "wands", num: 1,  zhName: "權杖王牌", aliases: ["ace","1","i","one","ace of wands","1 of wands","ace of rods","ace of staves"], zhAliases: ["權杖","權杖王牌","權杖一","王牌","權杖1"] },
  { name: "2 of Wands",          suit: "wands", num: 2,  zhName: "權杖二",   aliases: ["2","ii","two","two of wands","2 of wands","two of rods"],                     zhAliases: ["權杖","權杖二","權杖2"] },
  { name: "3 of Wands",          suit: "wands", num: 3,  zhName: "權杖三",   aliases: ["3","iii","three","three of wands","3 of wands","three of rods"],               zhAliases: ["權杖","權杖三","權杖3"] },
  { name: "4 of Wands",          suit: "wands", num: 4,  zhName: "權杖四",   aliases: ["4","iv","four","four of wands","4 of wands","four of rods"],                   zhAliases: ["權杖","權杖四","權杖4"] },
  { name: "5 of Wands",          suit: "wands", num: 5,  zhName: "權杖五",   aliases: ["5","v","five","five of wands","5 of wands","five of rods"],                   zhAliases: ["權杖","權杖五","權杖5"] },
  { name: "6 of Wands",          suit: "wands", num: 6,  zhName: "權杖六",   aliases: ["6","vi","six","six of wands","6 of wands","six of rods"],                     zhAliases: ["權杖","權杖六","權杖6"] },
  { name: "7 of Wands",          suit: "wands", num: 7,  zhName: "權杖七",   aliases: ["7","vii","seven","seven of wands","7 of wands","seven of rods"],               zhAliases: ["權杖","權杖七","權杖7"] },
  { name: "8 of Wands",          suit: "wands", num: 8,  zhName: "權杖八",   aliases: ["8","viii","eight","eight of wands","8 of wands","eight of rods"],             zhAliases: ["權杖","權杖八","權杖8"] },
  { name: "9 of Wands",          suit: "wands", num: 9,  zhName: "權杖九",   aliases: ["9","ix","nine","nine of wands","9 of wands","nine of rods"],                 zhAliases: ["權杖","權杖九","權杖9"] },
  { name: "10 of Wands",         suit: "wands", num: 10, zhName: "權杖十",   aliases: ["10","x","ten","ten of wands","10 of wands","ten of rods"],                   zhAliases: ["權杖","權杖十","權杖10"] },
  { name: "Page of Wands",       suit: "wands", num: 11, zhName: "權杖侍者", aliases: ["11","xi","page","page of wands","page of rods"],                             zhAliases: ["權杖","權杖侍者","侍者"] },
  { name: "Knight of Wands",     suit: "wands", num: 12, zhName: "權杖騎士", aliases: ["12","xii","knight","knight of wands","knight of rods"],                       zhAliases: ["權杖","權杖騎士","騎士"] },
  { name: "Queen of Wands",      suit: "wands", num: 13, zhName: "權杖王后", aliases: ["13","xiii","queen","queen of wands","queen of rods"],                         zhAliases: ["權杖","權杖王后","王后"] },
  { name: "King of Wands",       suit: "wands", num: 14, zhName: "權杖國王", aliases: ["14","xiv","king","king of wands","king of rods"],                           zhAliases: ["權杖","權杖國王","國王"] },

  // ── MINOR ARCANA — SWORDS ─────────────────────────────────────────────────
  { name: "1 of Swords",         suit: "swords", num: 1,  zhName: "寶劍王牌", aliases: ["ace","1","i","one","ace of swords","1 of swords"],         zhAliases: ["寶劍","寶劍王牌","寶劍一","王牌","寶劍1"] },
  { name: "2 of Swords",         suit: "swords", num: 2,  zhName: "寶劍二",   aliases: ["2","ii","two","two of swords","2 of swords"],               zhAliases: ["寶劍","寶劍二","寶劍2"] },
  { name: "3 of Swords",         suit: "swords", num: 3,  zhName: "寶劍三",   aliases: ["3","iii","three","three of swords","3 of swords"],           zhAliases: ["寶劍","寶劍三","寶劍3"] },
  { name: "4 of Swords",         suit: "swords", num: 4,  zhName: "寶劍四",   aliases: ["4","iv","four","four of swords","4 of swords"],             zhAliases: ["寶劍","寶劍四","寶劍4"] },
  { name: "5 of Swords",         suit: "swords", num: 5,  zhName: "寶劍五",   aliases: ["5","v","five","five of swords","5 of swords"],             zhAliases: ["寶劍","寶劍五","寶劍5"] },
  { name: "6 of Swords",         suit: "swords", num: 6,  zhName: "寶劍六",   aliases: ["6","vi","six","six of swords","6 of swords"],             zhAliases: ["寶劍","寶劍六","寶劍6"] },
  { name: "7 of Swords",         suit: "swords", num: 7,  zhName: "寶劍七",   aliases: ["7","vii","seven","seven of swords","7 of swords"],         zhAliases: ["寶劍","寶劍七","寶劍7"] },
  { name: "8 of Swords",         suit: "swords", num: 8,  zhName: "寶劍八",   aliases: ["8","viii","eight","eight of swords","8 of swords"],       zhAliases: ["寶劍","寶劍八","寶劍8"] },
  { name: "9 of Swords",         suit: "swords", num: 9,  zhName: "寶劍九",   aliases: ["9","ix","nine","nine of swords","9 of swords"],           zhAliases: ["寶劍","寶劍九","寶劍9"] },
  { name: "10 of Swords",        suit: "swords", num: 10, zhName: "寶劍十",   aliases: ["10","x","ten","ten of swords","10 of swords"],             zhAliases: ["寶劍","寶劍十","寶劍10"] },
  { name: "Page of Swords",      suit: "swords", num: 11, zhName: "寶劍侍者", aliases: ["11","xi","page","page of swords"],                         zhAliases: ["寶劍","寶劍侍者","侍者"] },
  { name: "Knight of Swords",    suit: "swords", num: 12, zhName: "寶劍騎士", aliases: ["12","xii","knight","knight of swords"],                     zhAliases: ["寶劍","寶劍騎士","騎士"] },
  { name: "Queen of Swords",     suit: "swords", num: 13, zhName: "寶劍王后", aliases: ["13","xiii","queen","queen of swords"],                     zhAliases: ["寶劍","寶劍王后","王后"] },
  { name: "King of Swords",      suit: "swords", num: 14, zhName: "寶劍國王", aliases: ["14","xiv","king","king of swords"],                       zhAliases: ["寶劍","寶劍國王","國王"] },

  // ── MINOR ARCANA — PENTACLES ──────────────────────────────────────────────
  { name: "1 of Pentacles",      suit: "pentacles", num: 1,  zhName: "錢幣王牌", aliases: ["ace","1","i","one","ace of pentacles","1 of pentacles","ace of coins","ace of disks"], zhAliases: ["錢幣","星幣","錢幣王牌","錢幣一","王牌","錢幣1"] },
  { name: "2 of Pentacles",      suit: "pentacles", num: 2,  zhName: "錢幣二",   aliases: ["2","ii","two","two of pentacles","2 of pentacles","two of coins"],                     zhAliases: ["錢幣","星幣","錢幣二","錢幣2"] },
  { name: "3 of Pentacles",      suit: "pentacles", num: 3,  zhName: "錢幣三",   aliases: ["3","iii","three","three of pentacles","3 of pentacles","three of coins"],               zhAliases: ["錢幣","星幣","錢幣三","錢幣3"] },
  { name: "4 of Pentacles",      suit: "pentacles", num: 4,  zhName: "錢幣四",   aliases: ["4","iv","four","four of pentacles","4 of pentacles","four of coins"],                   zhAliases: ["錢幣","星幣","錢幣四","錢幣4"] },
  { name: "5 of Pentacles",      suit: "pentacles", num: 5,  zhName: "錢幣五",   aliases: ["5","v","five","five of pentacles","5 of pentacles","five of coins"],                   zhAliases: ["錢幣","星幣","錢幣五","錢幣5"] },
  { name: "6 of Pentacles",      suit: "pentacles", num: 6,  zhName: "錢幣六",   aliases: ["6","vi","six","six of pentacles","6 of pentacles","six of coins"],                     zhAliases: ["錢幣","星幣","錢幣六","錢幣6"] },
  { name: "7 of Pentacles",      suit: "pentacles", num: 7,  zhName: "錢幣七",   aliases: ["7","vii","seven","seven of pentacles","7 of pentacles","seven of coins"],               zhAliases: ["錢幣","星幣","錢幣七","錢幣7"] },
  { name: "8 of Pentacles",      suit: "pentacles", num: 8,  zhName: "錢幣八",   aliases: ["8","viii","eight","eight of pentacles","8 of pentacles","eight of coins"],             zhAliases: ["錢幣","星幣","錢幣八","錢幣8"] },
  { name: "9 of Pentacles",      suit: "pentacles", num: 9,  zhName: "錢幣九",   aliases: ["9","ix","nine","nine of pentacles","9 of pentacles","nine of coins"],                 zhAliases: ["錢幣","星幣","錢幣九","錢幣9"] },
  { name: "10 of Pentacles",     suit: "pentacles", num: 10, zhName: "錢幣十",   aliases: ["10","x","ten","ten of pentacles","10 of pentacles","ten of coins"],                   zhAliases: ["錢幣","星幣","錢幣十","錢幣10"] },
  { name: "Page of Pentacles",   suit: "pentacles", num: 11, zhName: "錢幣侍者", aliases: ["11","xi","page","page of pentacles","page of coins"],                                 zhAliases: ["錢幣","星幣","錢幣侍者","侍者"] },
  { name: "Knight of Pentacles", suit: "pentacles", num: 12, zhName: "錢幣騎士", aliases: ["12","xii","knight","knight of pentacles","knight of coins"],                           zhAliases: ["錢幣","星幣","錢幣騎士","騎士"] },
  { name: "Queen of Pentacles",  suit: "pentacles", num: 13, zhName: "錢幣王后", aliases: ["13","xiii","queen","queen of pentacles","queen of coins"],                             zhAliases: ["錢幣","星幣","錢幣王后","王后"] },
  { name: "King of Pentacles",   suit: "pentacles", num: 14, zhName: "錢幣國王", aliases: ["14","xiv","king","king of pentacles","king of coins"],                               zhAliases: ["錢幣","星幣","錢幣國王","國王"] }
];
