const TAROT_DECK = [
  // ── MAJOR ARCANA ──────────────────────────────────────────────────────────
  { name: "0 The Fool",            suit: "major", num: 0,  aliases: ["0","zero","fool","the fool","0 the fool"] },
  { name: "I The Magician",        suit: "major", num: 1,  aliases: ["1","i","one","magician","the magician","i the magician"] },
  { name: "II The High Priestess", suit: "major", num: 2,  aliases: ["2","ii","two","high priestess","priestess","the high priestess","ii the high priestess"] },
  { name: "III The Empress",       suit: "major", num: 3,  aliases: ["3","iii","three","empress","the empress","iii the empress"] },
  { name: "IV The Emperor",        suit: "major", num: 4,  aliases: ["4","iv","four","emperor","the emperor","iv the emperor"] },
  { name: "V The Hierophant",      suit: "major", num: 5,  aliases: ["5","v","five","hierophant","pope","the hierophant","v the hierophant"] },
  { name: "VI The Lovers",         suit: "major", num: 6,  aliases: ["6","vi","six","lovers","the lovers","vi the lovers"] },
  { name: "VII The Chariot",       suit: "major", num: 7,  aliases: ["7","vii","seven","chariot","the chariot","vii the chariot"] },
  { name: "VIII Strength",         suit: "major", num: 8,  aliases: ["8","viii","eight","strength","fortitude","viii strength"] },
  { name: "IX The Hermit",         suit: "major", num: 9,  aliases: ["9","ix","nine","hermit","the hermit","ix the hermit"] },
  { name: "X Wheel of Fortune",    suit: "major", num: 10, aliases: ["10","x","ten","wheel","wheel of fortune","fortune","x wheel of fortune"] },
  { name: "XI Justice",            suit: "major", num: 11, aliases: ["11","xi","eleven","justice","xi justice"] },
  { name: "XII The Hanged Man",    suit: "major", num: 12, aliases: ["12","xii","twelve","hanged man","hanged","the hanged man","xii the hanged man"] },
  { name: "XIII Death",            suit: "major", num: 13, aliases: ["13","xiii","thirteen","death","xiii death"] },
  { name: "XIV Temperance",        suit: "major", num: 14, aliases: ["14","xiv","fourteen","temperance","xiv temperance"] },
  { name: "XV The Devil",          suit: "major", num: 15, aliases: ["15","xv","fifteen","devil","the devil","xv the devil"] },
  { name: "XVI The Tower",         suit: "major", num: 16, aliases: ["16","xvi","sixteen","tower","the tower","xvi the tower"] },
  { name: "XVII The Star",         suit: "major", num: 17, aliases: ["17","xvii","seventeen","star","the star","xvii the star"] },
  { name: "XVIII The Moon",        suit: "major", num: 18, aliases: ["18","xviii","eighteen","moon","the moon","xviii the moon"] },
  { name: "XIX The Sun",           suit: "major", num: 19, aliases: ["19","xix","nineteen","sun","the sun","xix the sun"] },
  { name: "XX Judgement",          suit: "major", num: 20, aliases: ["20","xx","twenty","judgement","judgment","xx judgement"] },
  { name: "XXI The World",         suit: "major", num: 21, aliases: ["21","xxi","twenty one","twenty-one","world","the world","xxi the world"] },

  // ── MINOR ARCANA — CUPS ───────────────────────────────────────────────────
  { name: "1 of Cups",           suit: "cups", num: 1,  aliases: ["ace","1","i","one","ace of cups","1 of cups"] },
  { name: "2 of Cups",           suit: "cups", num: 2,  aliases: ["2","ii","two","two of cups","2 of cups"] },
  { name: "3 of Cups",           suit: "cups", num: 3,  aliases: ["3","iii","three","three of cups","3 of cups"] },
  { name: "4 of Cups",           suit: "cups", num: 4,  aliases: ["4","iv","four","four of cups","4 of cups"] },
  { name: "5 of Cups",           suit: "cups", num: 5,  aliases: ["5","v","five","five of cups","5 of cups"] },
  { name: "6 of Cups",           suit: "cups", num: 6,  aliases: ["6","vi","six","six of cups","6 of cups"] },
  { name: "7 of Cups",           suit: "cups", num: 7,  aliases: ["7","vii","seven","seven of cups","7 of cups"] },
  { name: "8 of Cups",           suit: "cups", num: 8,  aliases: ["8","viii","eight","eight of cups","8 of cups"] },
  { name: "9 of Cups",           suit: "cups", num: 9,  aliases: ["9","ix","nine","nine of cups","9 of cups"] },
  { name: "10 of Cups",          suit: "cups", num: 10, aliases: ["10","x","ten","ten of cups","10 of cups"] },
  { name: "Page of Cups",        suit: "cups", num: 11, aliases: ["11","xi","page","page of cups"] },
  { name: "Knight of Cups",      suit: "cups", num: 12, aliases: ["12","xii","knight","knight of cups"] },
  { name: "Queen of Cups",       suit: "cups", num: 13, aliases: ["13","xiii","queen","queen of cups"] },
  { name: "King of Cups",        suit: "cups", num: 14, aliases: ["14","xiv","king","king of cups"] },

  // ── MINOR ARCANA — WANDS ──────────────────────────────────────────────────
  { name: "1 of Wands",          suit: "wands", num: 1,  aliases: ["ace","1","i","one","ace of wands","1 of wands","ace of rods","ace of staves"] },
  { name: "2 of Wands",          suit: "wands", num: 2,  aliases: ["2","ii","two","two of wands","2 of wands","two of rods"] },
  { name: "3 of Wands",          suit: "wands", num: 3,  aliases: ["3","iii","three","three of wands","3 of wands","three of rods"] },
  { name: "4 of Wands",          suit: "wands", num: 4,  aliases: ["4","iv","four","four of wands","4 of wands","four of rods"] },
  { name: "5 of Wands",          suit: "wands", num: 5,  aliases: ["5","v","five","five of wands","5 of wands","five of rods"] },
  { name: "6 of Wands",          suit: "wands", num: 6,  aliases: ["6","vi","six","six of wands","6 of wands","six of rods"] },
  { name: "7 of Wands",          suit: "wands", num: 7,  aliases: ["7","vii","seven","seven of wands","7 of wands","seven of rods"] },
  { name: "8 of Wands",          suit: "wands", num: 8,  aliases: ["8","viii","eight","eight of wands","8 of wands","eight of rods"] },
  { name: "9 of Wands",          suit: "wands", num: 9,  aliases: ["9","ix","nine","nine of wands","9 of wands","nine of rods"] },
  { name: "10 of Wands",         suit: "wands", num: 10, aliases: ["10","x","ten","ten of wands","10 of wands","ten of rods"] },
  { name: "Page of Wands",       suit: "wands", num: 11, aliases: ["11","xi","page","page of wands","page of rods"] },
  { name: "Knight of Wands",     suit: "wands", num: 12, aliases: ["12","xii","knight","knight of wands","knight of rods"] },
  { name: "Queen of Wands",      suit: "wands", num: 13, aliases: ["13","xiii","queen","queen of wands","queen of rods"] },
  { name: "King of Wands",       suit: "wands", num: 14, aliases: ["14","xiv","king","king of wands","king of rods"] },

  // ── MINOR ARCANA — SWORDS ─────────────────────────────────────────────────
  { name: "1 of Swords",         suit: "swords", num: 1,  aliases: ["ace","1","i","one","ace of swords","1 of swords"] },
  { name: "2 of Swords",         suit: "swords", num: 2,  aliases: ["2","ii","two","two of swords","2 of swords"] },
  { name: "3 of Swords",         suit: "swords", num: 3,  aliases: ["3","iii","three","three of swords","3 of swords"] },
  { name: "4 of Swords",         suit: "swords", num: 4,  aliases: ["4","iv","four","four of swords","4 of swords"] },
  { name: "5 of Swords",         suit: "swords", num: 5,  aliases: ["5","v","five","five of swords","5 of swords"] },
  { name: "6 of Swords",         suit: "swords", num: 6,  aliases: ["6","vi","six","six of swords","6 of swords"] },
  { name: "7 of Swords",         suit: "swords", num: 7,  aliases: ["7","vii","seven","seven of swords","7 of swords"] },
  { name: "8 of Swords",         suit: "swords", num: 8,  aliases: ["8","viii","eight","eight of swords","8 of swords"] },
  { name: "9 of Swords",         suit: "swords", num: 9,  aliases: ["9","ix","nine","nine of swords","9 of swords"] },
  { name: "10 of Swords",        suit: "swords", num: 10, aliases: ["10","x","ten","ten of swords","10 of swords"] },
  { name: "Page of Swords",      suit: "swords", num: 11, aliases: ["11","xi","page","page of swords"] },
  { name: "Knight of Swords",    suit: "swords", num: 12, aliases: ["12","xii","knight","knight of swords"] },
  { name: "Queen of Swords",     suit: "swords", num: 13, aliases: ["13","xiii","queen","queen of swords"] },
  { name: "King of Swords",      suit: "swords", num: 14, aliases: ["14","xiv","king","king of swords"] },

  // ── MINOR ARCANA — PENTACLES ──────────────────────────────────────────────
  { name: "1 of Pentacles",      suit: "pentacles", num: 1,  aliases: ["ace","1","i","one","ace of pentacles","1 of pentacles","ace of coins","ace of disks"] },
  { name: "2 of Pentacles",      suit: "pentacles", num: 2,  aliases: ["2","ii","two","two of pentacles","2 of pentacles","two of coins"] },
  { name: "3 of Pentacles",      suit: "pentacles", num: 3,  aliases: ["3","iii","three","three of pentacles","3 of pentacles","three of coins"] },
  { name: "4 of Pentacles",      suit: "pentacles", num: 4,  aliases: ["4","iv","four","four of pentacles","4 of pentacles","four of coins"] },
  { name: "5 of Pentacles",      suit: "pentacles", num: 5,  aliases: ["5","v","five","five of pentacles","5 of pentacles","five of coins"] },
  { name: "6 of Pentacles",      suit: "pentacles", num: 6,  aliases: ["6","vi","six","six of pentacles","6 of pentacles","six of coins"] },
  { name: "7 of Pentacles",      suit: "pentacles", num: 7,  aliases: ["7","vii","seven","seven of pentacles","7 of pentacles","seven of coins"] },
  { name: "8 of Pentacles",      suit: "pentacles", num: 8,  aliases: ["8","viii","eight","eight of pentacles","8 of pentacles","eight of coins"] },
  { name: "9 of Pentacles",      suit: "pentacles", num: 9,  aliases: ["9","ix","nine","nine of pentacles","9 of pentacles","nine of coins"] },
  { name: "10 of Pentacles",     suit: "pentacles", num: 10, aliases: ["10","x","ten","ten of pentacles","10 of pentacles","ten of coins"] },
  { name: "Page of Pentacles",   suit: "pentacles", num: 11, aliases: ["11","xi","page","page of pentacles","page of coins"] },
  { name: "Knight of Pentacles", suit: "pentacles", num: 12, aliases: ["12","xii","knight","knight of pentacles","knight of coins"] },
  { name: "Queen of Pentacles",  suit: "pentacles", num: 13, aliases: ["13","xiii","queen","queen of pentacles","queen of coins"] },
  { name: "King of Pentacles",   suit: "pentacles", num: 14, aliases: ["14","xiv","king","king of pentacles","king of coins"] }
];
