<script>
const TAROT_DECK = [
  // ── MAJOR ARCANA ──────────────────────────────────────────────────────────
  { name: "The Fool",            suit: "major", num: 0,  aliases: ["0","zero","fool","the fool"] },
  { name: "The Magician",        suit: "major", num: 1,  aliases: ["1","i","one","magician","the magician"] },
  { name: "The High Priestess",  suit: "major", num: 2,  aliases: ["2","ii","two","high priestess","priestess","the high priestess"] },
  { name: "The Empress",         suit: "major", num: 3,  aliases: ["3","iii","three","empress","the empress"] },
  { name: "The Emperor",         suit: "major", num: 4,  aliases: ["4","iv","four","emperor","the emperor"] },
  { name: "The Hierophant",      suit: "major", num: 5,  aliases: ["5","v","five","hierophant","pope","the hierophant"] },
  { name: "The Lovers",          suit: "major", num: 6,  aliases: ["6","vi","six","lovers","the lovers"] },
  { name: "The Chariot",         suit: "major", num: 7,  aliases: ["7","vii","seven","chariot","the chariot"] },
  { name: "Strength",            suit: "major", num: 8,  aliases: ["8","viii","eight","strength","fortitude"] },
  { name: "The Hermit",          suit: "major", num: 9,  aliases: ["9","ix","nine","hermit","the hermit"] },
  { name: "Wheel of Fortune",    suit: "major", num: 10, aliases: ["10","x","ten","wheel","wheel of fortune","fortune"] },
  { name: "Justice",             suit: "major", num: 11, aliases: ["11","xi","eleven","justice"] },
  { name: "The Hanged Man",      suit: "major", num: 12, aliases: ["12","xii","twelve","hanged man","hanged","the hanged man"] },
  { name: "Death",               suit: "major", num: 13, aliases: ["13","xiii","thirteen","death"] },
  { name: "Temperance",          suit: "major", num: 14, aliases: ["14","xiv","fourteen","temperance"] },
  { name: "The Devil",           suit: "major", num: 15, aliases: ["15","xv","fifteen","devil","the devil"] },
  { name: "The Tower",           suit: "major", num: 16, aliases: ["16","xvi","sixteen","tower","the tower"] },
  { name: "The Star",            suit: "major", num: 17, aliases: ["17","xvii","seventeen","star","the star"] },
  { name: "The Moon",            suit: "major", num: 18, aliases: ["18","xviii","eighteen","moon","the moon"] },
  { name: "The Sun",             suit: "major", num: 19, aliases: ["19","xix","nineteen","sun","the sun"] },
  { name: "Judgement",           suit: "major", num: 20, aliases: ["20","xx","twenty","judgement","judgment"] },
  { name: "The World",           suit: "major", num: 21, aliases: ["21","xxi","twenty one","twenty-one","world","the world"] },

  // ── MINOR ARCANA — CUPS ───────────────────────────────────────────────────
  { name: "Ace of Cups",         suit: "cups", num: 1,  aliases: ["ace","1","i","one","ace of cups","1 of cups"] },
  { name: "Two of Cups",         suit: "cups", num: 2,  aliases: ["2","ii","two","two of cups","2 of cups"] },
  { name: "Three of Cups",       suit: "cups", num: 3,  aliases: ["3","iii","three","three of cups","3 of cups"] },
  { name: "Four of Cups",        suit: "cups", num: 4,  aliases: ["4","iv","four","four of cups","4 of cups"] },
  { name: "Five of Cups",        suit: "cups", num: 5,  aliases: ["5","v","five","five of cups","5 of cups"] },
  { name: "Six of Cups",         suit: "cups", num: 6,  aliases: ["6","vi","six","six of cups","6 of cups"] },
  { name: "Seven of Cups",       suit: "cups", num: 7,  aliases: ["7","vii","seven","seven of cups","7 of cups"] },
  { name: "Eight of Cups",       suit: "cups", num: 8,  aliases: ["8","viii","eight","eight of cups","8 of cups"] },
  { name: "Nine of Cups",        suit: "cups", num: 9,  aliases: ["9","ix","nine","nine of cups","9 of cups"] },
  { name: "Ten of Cups",         suit: "cups", num: 10, aliases: ["10","x","ten","ten of cups","10 of cups"] },
  { name: "Page of Cups",        suit: "cups", num: 11, aliases: ["11","xi","page","page of cups"] },
  { name: "Knight of Cups",      suit: "cups", num: 12, aliases: ["12","xii","knight","knight of cups"] },
  { name: "Queen of Cups",       suit: "cups", num: 13, aliases: ["13","xiii","queen","queen of cups"] },
  { name: "King of Cups",        suit: "cups", num: 14, aliases: ["14","xiv","king","king of cups"] },

  // ── MINOR ARCANA — WANDS ──────────────────────────────────────────────────
  { name: "Ace of Wands",        suit: "wands", num: 1,  aliases: ["ace","1","i","one","ace of wands","1 of wands","ace of rods","ace of staves"] },
  { name: "Two of Wands",        suit: "wands", num: 2,  aliases: ["2","ii","two","two of wands","2 of wands","two of rods"] },
  { name: "Three of Wands",      suit: "wands", num: 3,  aliases: ["3","iii","three","three of wands","3 of wands","three of rods"] },
  { name: "Four of Wands",       suit: "wands", num: 4,  aliases: ["4","iv","four","four of wands","4 of wands","four of rods"] },
  { name: "Five of Wands",       suit: "wands", num: 5,  aliases: ["5","v","five","five of wands","5 of wands","five of rods"] },
  { name: "Six of Wands",        suit: "wands", num: 6,  aliases: ["6","vi","six","six of wands","6 of wands","six of rods"] },
  { name: "Seven of Wands",      suit: "wands", num: 7,  aliases: ["7","vii","seven","seven of wands","7 of wands","seven of rods"] },
  { name: "Eight of Wands",      suit: "wands", num: 8,  aliases: ["8","viii","eight","eight of wands","8 of wands","eight of rods"] },
  { name: "Nine of Wands",       suit: "wands", num: 9,  aliases: ["9","ix","nine","nine of wands","9 of wands","nine of rods"] },
  { name: "Ten of Wands",        suit: "wands", num: 10, aliases: ["10","x","ten","ten of wands","10 of wands","ten of rods"] },
  { name: "Page of Wands",       suit: "wands", num: 11, aliases: ["11","xi","page","page of wands","page of rods"] },
  { name: "Knight of Wands",     suit: "wands", num: 12, aliases: ["12","xii","knight","knight of wands","knight of rods"] },
  { name: "Queen of Wands",      suit: "wands", num: 13, aliases: ["13","xiii","queen","queen of wands","queen of rods"] },
  { name: "King of Wands",       suit: "wands", num: 14, aliases: ["14","xiv","king","king of wands","king of rods"] },

  // ── MINOR ARCANA — SWORDS ─────────────────────────────────────────────────
  { name: "Ace of Swords",       suit: "swords", num: 1,  aliases: ["ace","1","i","one","ace of swords","1 of swords"] },
  { name: "Two of Swords",       suit: "swords", num: 2,  aliases: ["2","ii","two","two of swords","2 of swords"] },
  { name: "Three of Swords",     suit: "swords", num: 3,  aliases: ["3","iii","three","three of swords","3 of swords"] },
  { name: "Four of Swords",      suit: "swords", num: 4,  aliases: ["4","iv","four","four of swords","4 of swords"] },
  { name: "Five of Swords",      suit: "swords", num: 5,  aliases: ["5","v","five","five of swords","5 of swords"] },
  { name: "Six of Swords",       suit: "swords", num: 6,  aliases: ["6","vi","six","six of swords","6 of swords"] },
  { name: "Seven of Swords",     suit: "swords", num: 7,  aliases: ["7","vii","seven","seven of swords","7 of swords"] },
  { name: "Eight of Swords",     suit: "swords", num: 8,  aliases: ["8","viii","eight","eight of swords","8 of swords"] },
  { name: "Nine of Swords",      suit: "swords", num: 9,  aliases: ["9","ix","nine","nine of swords","9 of swords"] },
  { name: "Ten of Swords",       suit: "swords", num: 10, aliases: ["10","x","ten","ten of swords","10 of swords"] },
  { name: "Page of Swords",      suit: "swords", num: 11, aliases: ["11","xi","page","page of swords"] },
  { name: "Knight of Swords",    suit: "swords", num: 12, aliases: ["12","xii","knight","knight of swords"] },
  { name: "Queen of Swords",     suit: "swords", num: 13, aliases: ["13","xiii","queen","queen of swords"] },
  { name: "King of Swords",      suit: "swords", num: 14, aliases: ["14","xiv","king","king of swords"] },

  // ── MINOR ARCANA — PENTACLES ──────────────────────────────────────────────
  { name: "Ace of Pentacles",    suit: "pentacles", num: 1,  aliases: ["ace","1","i","one","ace of pentacles","1 of pentacles","ace of coins","ace of disks"] },
  { name: "Two of Pentacles",    suit: "pentacles", num: 2,  aliases: ["2","ii","two","two of pentacles","2 of pentacles","two of coins"] },
  { name: "Three of Pentacles",  suit: "pentacles", num: 3,  aliases: ["3","iii","three","three of pentacles","3 of pentacles","three of coins"] },
  { name: "Four of Pentacles",   suit: "pentacles", num: 4,  aliases: ["4","iv","four","four of pentacles","4 of pentacles","four of coins"] },
  { name: "Five of Pentacles",   suit: "pentacles", num: 5,  aliases: ["5","v","five","five of pentacles","5 of pentacles","five of coins"] },
  { name: "Six of Pentacles",    suit: "pentacles", num: 6,  aliases: ["6","vi","six","six of pentacles","6 of pentacles","six of coins"] },
  { name: "Seven of Pentacles",  suit: "pentacles", num: 7,  aliases: ["7","vii","seven","seven of pentacles","7 of pentacles","seven of coins"] },
  { name: "Eight of Pentacles",  suit: "pentacles", num: 8,  aliases: ["8","viii","eight","eight of pentacles","8 of pentacles","eight of coins"] },
  { name: "Nine of Pentacles",   suit: "pentacles", num: 9,  aliases: ["9","ix","nine","nine of pentacles","9 of pentacles","nine of coins"] },
  { name: "Ten of Pentacles",    suit: "pentacles", num: 10, aliases: ["10","x","ten","ten of pentacles","10 of pentacles","ten of coins"] },
  { name: "Page of Pentacles",   suit: "pentacles", num: 11, aliases: ["11","xi","page","page of pentacles","page of coins"] },
  { name: "Knight of Pentacles", suit: "pentacles", num: 12, aliases: ["12","xii","knight","knight of pentacles","knight of coins"] },
  { name: "Queen of Pentacles",  suit: "pentacles", num: 13, aliases: ["13","xiii","queen","queen of pentacles","queen of coins"] },
  { name: "King of Pentacles",   suit: "pentacles", num: 14, aliases: ["14","xiv","king","king of pentacles","king of coins"] }
];
</script>